import prettier from 'eslint-config-prettier';
import js from '@eslint/js';
import { includeIgnoreFile } from '@eslint/compat';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import { fileURLToPath } from 'node:url';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url));

export default ts.config(
	includeIgnoreFile(gitignorePath),
	// vendored pdf.js modules keep upstream style (see src/lib/draft/type1/README.md)
	{ ignores: ['src/lib/draft/type1/*.js'] },
	// generated by the Paraglide compiler (paraglideVitePlugin in vite.config.ts), never hand-edited
	{ ignores: ['src/lib/paraglide/**'] },
	js.configs.recommended,
	...ts.configs.recommended,
	// eslint-plugin-svelte: flat-config presets live under 'flat/*'; 'recommended' is the
	// legacy-eslintrc object and is not spreadable
	...svelte.configs['flat/recommended'],
	prettier,
	...svelte.configs['flat/prettier'],
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			'no-undef': 'off',
			// Arrived with eslint 10 / eslint-plugin-svelte 3, all firing on code that predates
			// them: 73 hits across the app. Warnings rather than errors, so the upgrade does not
			// hide behind a mass rewrite - prefer-svelte-reactivity in particular swaps plain
			// Map/Set for reactive ones, which is a runtime change and wants its own pass.
			'svelte/prefer-svelte-reactivity': 'warn',
			'svelte/require-each-key': 'warn',
			'svelte/no-unused-props': 'warn',
			'svelte/no-useless-mustaches': 'warn',
			'svelte/no-dom-manipulating': 'warn',
			'no-useless-assignment': 'warn',
			'preserve-caught-error': 'warn',
			// underscore prefix = intentionally unused
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_'
				}
			]
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	// styles.md enforcement. Rules that the codebase already satisfies run as errors;
	// rules with existing violations run as warnings until their cleanup pass lands
	{
		files: ['src/**'],
		rules: {
			'func-style': ['warn', 'declaration'],
			'no-param-reassign': ['warn', { props: true }],
			'max-lines': ['warn', { max: 300, skipBlankLines: true, skipComments: true }],
			'id-length': ['error', { min: 1, max: 50 }],
			'id-denylist': [
				'warn',
				'data',
				'info',
				'obj',
				'tmp',
				'temp',
				'misc',
				'thing',
				'val',
				'arr',
				'foo',
				'helper',
				'helpers',
				'util',
				'utils'
			],
			'@typescript-eslint/consistent-type-definitions': ['warn', 'type']
		}
	},
	{
		files: ['src/**/*.ts'],
		rules: {
			'no-restricted-exports': ['warn', { restrictDefaultExports: { direct: true, named: true } }]
		}
	},
	// package-private folders: internals are importable only within their own folder
	{
		files: ['src/**'],
		ignores: ['src/lib/schema/latexPMSchema/**'],
		rules: {
			'no-restricted-imports': [
				'warn',
				{
					paths: [{ name: 'svelte/store', message: 'runes only; adapt a third-party store at the edge (styles.md)' }],
					patterns: [
						{
							group: ['**/latexPMSchema/*', '!**/latexPMSchema/latexPMSchema'],
							message: 'latexPMSchema internals are package-private; import through latexPMSchema.ts'
						}
					]
				}
			]
		}
	},
	{
		files: ['src/**/*.ts', 'src/**/*.svelte'],
		rules: {
			'@typescript-eslint/naming-convention': [
				'warn',
				// imported names are library-controlled; the deliberate CMView/PMView aliases live here too
				{ selector: 'import', format: null },
				// object keys often mirror external shapes (HTTP headers, CSS props, wire formats)
				{ selector: 'objectLiteralProperty', format: null },
				{ selector: 'typeProperty', format: null },
				{ selector: 'variable', modifiers: ['destructured'], format: null },
				// StrictPascalCase: variables holding Svelte components (lazy routes) are capitalized
				// by Svelte convention; allowDouble: build-injected globals like __APP_VERSION__
				{
					selector: 'variable',
					format: ['strictCamelCase', 'StrictPascalCase', 'UPPER_CASE'],
					leadingUnderscore: 'allowDouble',
					trailingUnderscore: 'allowDouble'
				},
				{ selector: 'function', format: ['strictCamelCase'] },
				{ selector: 'parameter', format: ['strictCamelCase'], leadingUnderscore: 'allow' },
				{ selector: 'classProperty', format: ['strictCamelCase', 'UPPER_CASE'], leadingUnderscore: 'allow' },
				{ selector: 'classMethod', format: ['strictCamelCase'] },
				{ selector: 'enumMember', format: ['UPPER_CASE'] },
				{ selector: 'interface', format: ['StrictPascalCase'], custom: { regex: '^I[A-Z]', match: false } },
				{ selector: 'class', format: ['StrictPascalCase'], custom: { regex: '^Abstract', match: false } },
				{ selector: 'typeLike', format: ['StrictPascalCase'] }
			]
		}
	}
);
